"""add audio_url to video_jobs

Revision ID: 06249c4990e2
Revises: df09cfafa24f
Create Date: 2026-01-16 02:57:31.798640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06249c4990e2'
down_revision: Union[str, None] = 'df09cfafa24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'audio_url')
    # ### end Alembic commands ###
